hosts:
  go: "https://gogoo.cyou"
  jsm: "https://jsm.one"
  maoyun: "https://maoyun2.com"
  hdong: "https://hdyun.cc"
  hx: "https://hxlm.io"
  ant: "https://antlink.xyz"
  mars: "https://marslink.org"
  nc: "https://naichayun.net"
  qy: "https://qingyun.io"
  azi: "https://azi.azzico.cc"
  light: "https://mi.xiaomizao.cc"
  km: "https://base.kuaimao.io"
  qz: "https://base.qingzhou.world"
  lv: "https://lvdengjiasu.top"
  gs: "https://gscloud.icu"
  grd: "https://grdcloud.com"
  xz: "https://api.xianzheyun.top"
  mce: "https://mcecloud.net"
  rock: "https://58rocket.com"
  moc: "https://mocv2.com"
  bl: "https://sulian.info"
  bl2: "https://ssp.sulian.info"
  kj: "https://520ape.com"

xbn:
  - "hx"
  - "nc"

replace:
  enabled: true
  values:
    - from: "qy-m.ikookook.com"
      to: "tt3.interesting2026.blog"
    - from: "qy-hk.kunlun06dns.com"
      to: "n1.good2026.com"
    - from: "qy-us.kunlun06dns.com"
      to: "mm.interesting2026.blog"
    - from: "qy-us.kunlun06dns.com"
      to: "tt3.interesting2026.blog"      
    - from: "qy-jp.kunlun06dns.com"
      to: "tt3.interesting2026.blog"
    - from: "qy-kr.kunlun06dns.com"
      to: "mm.interesting2026.blog"
    - from: "qy-sg.kunlun06dns.com"
      to: "mm.interesting2026.blog"
    - from: "n2.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "x2.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "mm.good2026.com"
      to: "tt3.interesting2026.blog"
    - from: "tt.good2026.com"
      to: "tt3.interesting2026.blog"
