hosts:
  go: "https://gogoo.cyou"
  jsm: "https://jsm.one"
  maoyun: "https://maoyun2.com"
  hdong: "https://hdyun.cc"
  hx: "https://hxlm.io"
  ant: "https://antlink.xyz"
  mars: "https://marslink.org"
  nc: "https://naichayun.net"
  qy: "https://qingyun.io"
  azi: "https://azi.azzico.cc"
  light: "https://mi.xiaomizao.cc"
  km: "https://base.kuaimao.io"
  qz: "https://base.qingzhou.world"
  gs: "https://gscloud.icu"
  grd: "https://grdcloud.com"
  xz: "https://api.xianzheyun.top"
  mce: "https://mcecloud.net"
  rock: "https://58rocket.com"
  moc: "https://mocv2.com"
  bl: "https://sulian.info"

xbn:
  - "hx"
  - "nc"

dns:
  enabled: true
  upstream:
    - 223.5.5.5
    - 119.29.29.29
  policy: 
    - "https://abc.xhonor.top:9066/dns-query"
  target: xx.interesting202603.com
  allowed:
    - "+.good2026.com"

block:
  enabled: true
  value: "mm.interesting2026.blog"

replace:
  enabled: false
  values:
    - from: "n1.good2026.com"
      to: "xx.interesting202602.com"
    - from: "n2.good2026.com"
      to: "xx.interesting202602.com"
    - from: "x1.good2026.com"
      to: "xx.interesting202602.com"
    - from: "x2.good2026.com"
      to: "xx.interesting202602.com"
    - from: "mm.good2026.com"
      to: "xx.interesting202602.com"
    - from: "tt.good2026.com"
      to: "xx.interesting202602.com"

replace-digilink:
  enabled: true
  values:
    - from: "n1.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "n2.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "x1.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "x2.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "mm.good2026.com"
      to: "nn2.interesting2026.blog"
    - from: "tt.good2026.com"
      to: "nn2.interesting2026.blog"
